// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhSDSX4ymi3kFxN_IobAXTLIInoUboCbM',
    appId: '1:579335202215:web:6de0de8060720e2193c282',
    messagingSenderId: '579335202215',
    projectId: 'budget-app4',
    authDomain: 'budget-app4.firebaseapp.com',
    storageBucket: 'budget-app4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3lV1HDP3lplSsaFO5UIJjJXplmTe-870',
    appId: '1:579335202215:android:e9cb5e30934ef65493c282',
    messagingSenderId: '579335202215',
    projectId: 'budget-app4',
    storageBucket: 'budget-app4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiwNztLXWleqOqx6lN2ImnWYDqX4DX9ic',
    appId: '1:579335202215:ios:25b07122412f28fc93c282',
    messagingSenderId: '579335202215',
    projectId: 'budget-app4',
    storageBucket: 'budget-app4.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhSDSX4ymi3kFxN_IobAXTLIInoUboCbM',
    appId: '1:579335202215:web:0af20270f4781db393c282',
    messagingSenderId: '579335202215',
    projectId: 'budget-app4',
    authDomain: 'budget-app4.firebaseapp.com',
    storageBucket: 'budget-app4.appspot.com',
  );
}
